### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by singhaditya28**
Updated for better stability and security

### CODE REVIEW

**Comment by chantra** [comment]
Thanks @singhaditya28 

This seems like a rather generic .gitignore and probably does not apply to this project. Is there any specific files/folders that are not filtered out by the current .gitignore and that you think should? If so, can you add those specifically?

Thanks

**Comment by singhaditya28** [comment]
@chantra .Sir there are many files which which are not contained in the project as such but are created on the client side. That's why I want to update the stability and security measures of as many projects as I can. So please accept my proposed changes. I have tested this file and it faces no crashes as such.

**Comment by chantra** [comment]
@singhaditya28 I understand that those files may be created such as when
building pip package, running tests... but those are already filtered out
with the current .gitignore. Your PR as a boatload of new files that likely
don’t apply here so while I appreciate your PR, I don’t know what it is
solving. I would rather keep the .gitignore to only contain path that need
to be filtered out.
You mention better stability and security in your PR, what is it referring
to?
Thanks

**Comment by singhaditya28** [comment]
@chantra If you want some edits in the file, you can surely ask them. My claim for better security & stability was to remove the possibility of disclosure of any information to the client which was to be essentially kept  secret. 👍 😃 .

**Comment by chantra** [comment]
Hi @singhaditya28 ,

While I do appreciate the effort and intention in submitting this PR. I am still not sure if it applies here.
We should leave what pertain to this project in this .gitignore file, people that are concerned about files that apply to **any** projects should probably set those entries via [`~/.gitconfig`'s `core.excludesFile` directive](https://git-scm.com/docs/gitignore).

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.

**Pull request closed without merging**
